/*
 * File: app/store/MyJsonStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MyJsonStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Item'
    ],

    config: {
        data: [
            {
                item: 'list item 1',
                album: 'Doc at the Radar Station',
                title: 'Hot Head'
            },
            {
                item: 'list item 1',
                album: 'Doc at the Radar Station',
                title: 'Ashtray Heart'
            },
            {
                item: 'list item 1',
                album: 'Doc at the Radar Station',
                title: 'A Carrot Is as Close as a Rabbit Gets to a Diamond'
            },
            {
                item: 'list item 1',
                album: 'Doc at the Radar Station',
                title: 'Run Paint Run Run'
            },
            {
                item: 'list item 1',
                album: 'Doc at the Radar Station',
                title: 'Sue Egypt'
            },
            {
                item: 'list item 1',
                album: 'Ice Cream for Crow',
                title: 'Ice Cream for Crow'
            },
            {
                item: 'list item 1',
                album: 'Ice Cream for Crow',
                title: 'The Host, the Ghost, the Most Holy O'
            },
            {
                item: 'list item 1',
                album: 'Ice Cream for Crow',
                title: 'Semi-Multicoloured Caucasian'
            },
            {
                item: 'list item 1',
                album: 'Ice Cream for Crow',
                title: 'Hey Garland, I Dig Your Tweed Coat'
            },
            {
                item: 'list item 1',
                album: 'Ice Cream for Crow',
                title: 'Evening Bell'
            },
            {
                item: 'list item 1',
                album: 'Unconditionally Guaranteed',
                title: 'Upon the Me-O-My'
            },
            {
                item: 'list item 1',
                album: 'Unconditionally Guaranteed',
                title: 'Sugar Bowl'
            },
            {
                item: 'list item 1',
                album: 'Unconditionally Guaranteed',
                title: 'New Electric Ride'
            },
            {
                item: 'list item 1',
                album: 'Unconditionally Guaranteed',
                title: 'Magic Be'
            },
            {
                item: 'list item 1',
                album: 'Unconditionally Guaranteed',
                title: 'Happy Love Song'
            }
        ],
        model: 'MyApp.model.Item',
        storeId: 'MyJsonStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'json'
            }
        },
        grouper: {
            property: 'album'
        }
    }
});