/*
 * File: app/view/MyList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.mylist',

    requires: [
        'MyApp.view.override.MyList'
    ],

    config: {
        style: 'background: #f6f6f6;',
        store: 'MyJsonStore',
        grouped: true,
        itemTpl: [
            '<div style="">{title}</div>'
        ],
        listeners: [
            {
                fn: 'onListInitialize',
                event: 'initialize'
            }
        ]
    },

    onListInitialize: function(component, eOpts) {
        /* The image is added via an override and scroll docked to the top.  
        ** Check the overrides class for the 

        */
        var scroller = component.getScrollable().getScroller(),
            image = Ext.ComponentQuery.query('#image')[0];

        scroller.on('scroll', function(scroll) {
            //console.log(scroll.position.y);
            image.setStyle('-webkit-transform: translate3d(0px, '+scroll.position.y / 3+'px, 0px);');
            //image.setStyle('filter: blur('+scroll.position+'px);');
        });
    }

});